### PR TITLE
Remove underlines when a buffer is selected

### PR DESCRIPTION
**Pull request by hankertrix**
This is a subjective change, so feel free to close this pull request if it is not up to your taste.

I prefer the look of having no underlines, mostly because the modified icon is also underlined, which doesn't look good. Below is a comparison:

Underlined:
image

No underlines:
image

### CODE REVIEW

**Comment by uloco** [comment]
Removing the underline for the modified only did not make you happy? As I wrote elsewhere, theming bufferline is hard. That's why I added the selected underline, because it mimics the default I guess. I'm fine with no underline for modified icon, but why is there a gap between? I had this look like that when I was testing with lushify, looked better when I restarted nvim...
The underline for the whole tab is nice though dunno. Need to test this

**Comment by uloco** [comment]
Also how did you like it when there was no custom bufferline theme, before my recent change?

**Comment by hankertrix** [comment]
> Removing the underline for the modified only did not make you happy?

Just removing the underline for the modified icon would be great, but I have no idea how to do that. It might not be possible, but I'm not sure.

> but why is there a gap between?

I'm not sure about this, I'm only using this theme with no other changes to bufferline.

<hr>

> Also how did you like it when there was no custom bufferline theme, before my recent change?

The default configuration worked well for me. It looked like this:

image
image
image
image

The selected tab being bold and italicised works surprisingly well for highlighting that it is selected, and the modified icon stood out very clearly against the background. However, the changes to the LSP diagnostics with the new highlights are better because even the non-selected files are coloured, which is very useful for me.

**Comment by uloco** [comment]
Oh I thought there was an underline... ok. Will give it a try.

**Comment by uloco** [comment]
are you using another plugin or so? when i checkout main, the selected buffer is always underlined, even with this change

**Comment by uloco** [comment]
oh i see, you can disable it in the setup of bufferline. i am using indicator style underline in my config

**Comment by uloco** [comment]
I'll keep this open until I figure out how to do this properly

**Comment by hankertrix** [comment]
> oh i see, you can disable it in the setup of bufferline. i am using indicator style underline in my config

Ah, my configuration uses the default, which should be `icon`.

**Pull request closed without merging**
