### PR TITLE
Swapped bg and fg colors for MatchParen

### LINKED ISSUE #29: Improve matched paren colors
see https://www.reddit.com/r/neovim/comments/10f77rh/comment/j50vkoy/?utm_source=share&utm_medium=web2x&context=3

### PR DESCRIPTION
**Pull request by LeviticusNelson**
fixes #29

### CODE REVIEW

**Comment by uloco** [comment]
Thanks for this PR, but I don't think this improves it but worsens it tbh. Now its even harder to see where the other brace is.

**Comment by uloco** [comment]
Is your cursor highlighted yellow correctly everywhere? 
The cursor should be always yellow in dark mode and always red in light mode.
If you are using gui neovim, probably it is not working as expected. 

It should look like this


**Normal mode**
Screenshot 2023-01-23 at 09 43 27

**Insert Mode**
Screenshot 2023-01-23 at 09 43 32

**Comment by LeviticusNelson** [comment]
I use the alacritty terminal and this is what it looks like
Screenshot 2023-01-23 at 8 40 44 AM
The highlighting was switched before so it looked like my cursor jumped to the opposite paren, which made it disorienting for me. 
I guess it has to do with my editor overriding the cursor color.

**Comment by uloco** [comment]
It's the `Cursor` highlight group, but looks like alacritty is using your configured theme instead the neovim one. I have the bluloco theme for iTerm and did not realise this is an issue. probably also other terminal emulators have this problem. will elaborate.

**Comment by uloco** [comment]
yes it looks like, neovim only applies this setting in the internal terminal. ok I'm not sure if I can theme the cursor as I wish like this.

**Comment by LeviticusNelson** [comment]
That's a bummer 🙁

**Comment by uloco** [comment]
I'll futher investigate. There should be a way to do this 😅

**Comment by uloco** [comment]
Already found something here
https://github.com/neovim/neovim/wiki/FAQ#how-to-change-cursor-color-in-the-terminal

**Comment by LeviticusNelson** [comment]
I guess another thing is that you should consider those who use tmux as well.

**Comment by uloco** [comment]
I will close this MR now, since it is not the solution to the problem. Will look into it and solve it soon hopefully!
I want to add bluloco themes for iterm, alacritty, kitty and also tmux. but there is also the cursor setting override I want to try. Will probably become default on and optional opt-out.

**Comment by uloco** [comment]
You can see progress when the ticket gets closed. Thanks again for pointing this  out. I was totally unaware of this, and it basically affects every user.

**Pull request closed without merging**
