### PR TITLE
Add support for fzf-lua

### PR DESCRIPTION
**Pull request by hankertrix**
For the colours to apply to the fzf window, you need to pass `fzf_colors = true` in the setup function for [`fzf-lua`](https://github.com/ibhagwan/fzf-lua).

Also reformatted the `README.md` file using prettier.

The colours are based on the [Telescope profile for `fzf-lua`](https://github.com/ibhagwan/fzf-lua/blob/ce978474e406f4faacd2e66ec35d93b9e8ae069e/lua/fzf-lua/profiles/telescope.lua#L25-L58), so the `fzf-lua` colours look as close as to the Telescope one.

Some screenshots of the [default fzf profile](https://github.com/ibhagwan/fzf-lua?tab=readme-ov-file#profiles) (the Telescope profile looks different):

image
image
image

### CODE REVIEW

**Comment by uloco** [comment]
Hey thank you for this :) 
The telescope colors I themed look different though, at least what I remember. I'm not on my laptop rn so I'll have a look later. Thanks a lot!! 🙏😊

**Comment by uloco** [comment]
My telescope colors look like this
Screenshot 2024-11-26 at 10 21 28
Screenshot 2024-11-26 at 10 21 36

**Comment by uloco** [comment]
oh lol, I didn't get that part that the colors are different than the screenshots :D sorry. I'll check on my setup with this change and let you know :)

**Comment by hankertrix** [comment]
No worries. The live grep colours are definitely different. As for the other types, I think they should be the same as I set them to the Telescope colours.

The live grep symbol matching highlight group should be controlled by this highlight group `FzfLuaLiveSym`. Let me know if you want it changed to the same highlight for the other modes.

As for the files in the live grep, I'm currently not sure what highlight group is controlling the highlight for that. I'm also not sure how to theme the file counter on the side, there doesn't seem to be a highlight group for that.

Here are all the highlight groups that are available to theme:
https://github.com/ibhagwan/fzf-lua?tab=readme-ov-file#highlights

**Comment by uloco** [comment]
Not sure if I set it up correctly. could you post a screenshot of how for example `files` looks for you?

**Comment by hankertrix** [comment]
Sure, here is how `files` look like:

image

`live_grep`:

image

`registers`:

image

`buffers`:

image

I am using [Wezterm](https://github.com/wez/wezterm) with the Bluloco Dark theme.

**Comment by hankertrix** [comment]
Here is my lazy.nvim config for fzf-lua:

```lua
return {
    "ibhagwan/fzf-lua",
    cond = utils.firenvim_not_active,
    lazy = true,
    cmd = "FzfLua",
    dependencies = {
        { "nvim-tree/nvim-web-devicons" },
        "trouble.nvim",
    },
    config = function()
        --

        -- Get the fzf-lua actions for trouble
        local trouble_actions = require("trouble.sources.fzf").actions

        -- Set up fzf-lua
        require("fzf-lua").setup({

            -- Use the theme colours for the fzf window
            fzf_colors = true,

            keymap = {

                builtin = {

                    -- Inherit the default mappings
                    true,
                    ["<C-j>"] = "preview-page-down",
                    ["<C-k>"] = "preview-page-up",
                    ["<M-j>"] = "preview-down",
                    ["<M-k>"] = "preview-up",
                },

                fzf = {

                    -- Inherit the default mappings
                    true,
                    ["ctrl-j"] = "preview-down",
                    ["ctrl-k"] = "preview-up",
                },
            },

            actions = {
                files = {

                    -- Inherit the default mappings
                    true,
                    ["ctrl-d"] = trouble_actions.open,
                },
            },
        })
    end,
    keys = {
        {
            "<F1>",
            function()
                require("fzf-lua").helptags()
            end,
            mode = { "n", "x", "i" },
            desc = "Search through the help text using the fuzzy finder",
        },
        {
            "<Leader>pf",
            function()
                require("fzf-lua").files()
            end,
            mode = "n",
            desc = "Find files using the fuzzy finder",
        },
        {
            "<Leader>ps",
            function()
                require("fzf-lua").live_grep()
            end,
            mode = "n",
            desc = "Search within files for a string",
        },
        {
            "<Leader>pb",
            function()
                require("fzf-lua").buffers()
            end,
            mode = "n",
            desc = "Search for open buffers using the fuzzy finder",
        },
        {
            "<Leader>pr",
            function()
                require("fzf-lua").registers()
            end,
            mode = "n",
            desc = "Search through vim registers",
        },
    },
}
```

**Comment by uloco** [comment]
It looks like this for me...
Don't know what I'm doing wrong...

Screenshot 2024-11-28 at 13 42 58

I'm on iterm2 though. dunno if this is the issue.

**Comment by hankertrix** [comment]
I think you are missing this line in the `fzf-lua` configuration:

```lua
-- Use the theme colours for the fzf window
fzf_colors = true
```

So the minimal setup function for fzf-lua should be:

```lua
require("fzf-lua").setup({
    fzf_colors = true
})
```

Without that line, it looks like this for me:

image

I'm also using this pull request branch that has the `FzfLua` highlight groups set.

**Comment by uloco** [comment]
I had that configured but it did not work.. now it works lol. ty

**Comment by uloco** [comment]
There are lots of other highlights that you can theme, I am using the telescope highlights picker to show them all. Maybe helpful, but you probably already know...
Maybe you could also look into those to theme the ctrl-g part and the numbers etc.
also the red indicator on the left   could be cursor?

```lua
local builtin = require("telescope.builtin")
vim.keymap.set('n', '<leader>lH', function() builtin.highlights() end, opts)
```

light

image

dark

image

**Comment by hankertrix** [comment]
Ahhh, I see. What colours do you want for the header text and the key bind in the header? There's no precedent in Telescope for that.

This is the header key bind:
image

This is the header text:
image

The `fzf-lua` window:
image

I also can't seem to find the highlight group to theme the live grep colours. It is apparently not `FzfLuaLiveSym`.

The cursor at the side doesn't seem to be themeable through the plugin. It is the same cursor used when you use fzf in your terminal.

I'll ask the plugin developer for advice on how to theme it.

**Comment by uloco** [comment]
I'd go for orange / attribute color for the header key-bind, since I am using that for which-key.
Title is usually keyword blue, but dunno if it clashes with the highlight of match? (EDIT: we could also do the method green, since it is like an action... just decide what looks better ;) )
Thanks for looking into it, so nice of you mate :))))

**Comment by hankertrix** [comment]
Ah sure, I made the changes. Here's how the header text looks like with keyword blue:

image

Here's how it looks like with method green:

image

I think method green is better.

What colour would you like for the directory part of the matched file, and the file part of the matched file?

The default colour for the directory part of the matched file, `FzfLuaDirPart` highlight group:

image

The default colour for the file part of the matched file, `FzfLuaFilePart` highlight group:
image

Together:
image


However, I don't think I can theme the `live_grep` output or the cursor at the side, as that is themed using the terminal colours as `fzf-lua` just calls `fzf` in a terminal window.

You're welcome!

**Comment by hankertrix** [comment]
Sorry about this, I was trying to squash all the commits into a single commit.

Also, do update me on the colours below, I'll make the changes and it should be good to go.

> What colour would you like for the directory part of the matched file, and the file part of the matched file?
> 
> The default colour for the directory part of the matched file, `FzfLuaDirPart` highlight group:
> 
> image
> 
> The default colour for the file part of the matched file, `FzfLuaFilePart` highlight group: image
> 
> Together: image

**Comment by uloco** [comment]
Hey there, thanks. Let's go with the green then! Also for the file path, I think it's ok to have them like the defaults, just with the correct colors if not already so (comment and foreground). thank you so much :)

**Comment by hankertrix** [comment]
Okay I added the colours. The `FzfLuaFilePart` highlight group links to `@none` by default, so I linked it to foreground explicitly.

Here are the screenshots of the final colours:

`files` using the `FzfLuaFilePart` and `FzfLuaDirPart` highlight groups:

image

`files` using the default formatter (doesn't use `FzfLuaFilePart` and `FzfLuaDirPart` highlight groups):

image

`live_grep` (cannot be styled through highlight groups unfortunately):

image

`buffers`:

image

`registers`:

image

`lsp_document_symbols`:

image

`lsp_live_workspace_symbols` (`FzfLuaLiveSym` highlight group):

image

Original `lsp_live_workspace_symbols` (`FzfLuaLiveSym` highlight group, just for comparison):

image

You're very welcome! I love this colour scheme.

**Comment by uloco** [comment]
Looks good, tyvm.
There are still some left I guess for the buffer for example, you could theme the line numbers at the end of path to pink (number)

I think the telescope highlight I have shown you only shows the highlights that are available, so when you open fzflua buffers and show the available highlights afterwards, you can see more highlight groups available for example. The group I found for the line nr is `FzfLuaPathLineNr`.

I don't want to bother you, you already did enough... so only do this if you really want to. I can look into at at some point too if you want. Cheers!

**Comment by hankertrix** [comment]
Ah yes I missed that one. Just linked `FzfLuaPathLineNr` and `FzfLuaPathColNr` to `Number`.

Here's how `buffers` looks like now:

image

**Comment by uloco** [comment]
looks awesome :) what's with the commented out stuff in the code? Should we keep it? Is there anything you forgot to comment in again? Otherwise looks good to merge

**Comment by uloco** [comment]
Also you can find all highlight groups here as well. I think some may be still missed...
https://github.com/ibhagwan/fzf-lua?tab=readme-ov-file#highlights

**Comment by hankertrix** [comment]
Ahhh okay.

Because of this:

> Ah yes I missed that one. Just linked `FzfLuaPathLineNr` and `FzfLuaPathColNr` to `Number`.
> 
> Here's how `buffers` looks like now:
> 
> image

The line numbers and the column numbers look the same in `diagnostics`:

image

Here's the original for comparison:

image

I'm not sure if you would want them to have a different colour to differentiate them, but I think it will definitely help with readability.

The commented highlight groups are intentional, as those are the defaults for the highlight group, so there is no need to set them.

As for the other missing highlight groups, I'll probably need your opinion on them as there's no precedent. The rest are linked to highlight groups already defined in the theme, or have been styled.

`FzfLuaBufName` (the `bluloco.lua`):

image

`FzfLuaBufFlagCur` (the red `%`) and `FzfLuaBufFlagAlt` (the turquoise `#`):

image

`FzfLuaTabTitle` (the `Tab #1`) and `FzfLuaTabMarker` (the `<<`):

image

**Comment by uloco** [comment]
I think it's fine to keep both numbers the same.
For `FzfLuaBufName` you can just use foreground color.
`FzfLuaBufFlagCur` could be keyword (blue)
`FzfLuaBufFlagAlt` could be tag (darkblue)
`FzfLuaTabTitle` in light blue is nice, could be param color (light blue)
`FzfLuaTabMarker` could be keyword too

**Comment by hankertrix** [comment]
Okay updated.

Here is how `lines` look now (`FzfLuaBufName`):

image

`buffers` (`FzfLuaBufFlagCur` and `FzfLuaBufFlagAlt`):

image

`tabs` (`FzfLuaTabTitle` and `FzfLuaTabMarker`):

image

Ignore the change in the prompt, that's a configuration change on my end, nothing to do with the theme.

**Comment by uloco** [comment]
Looks good :) Let's merge this beat :)

**Pull request merged**
