### PR TITLE
Fixes leap label highlight

### PR DESCRIPTION
**Pull request by guoliang**
This PR fixes the following issue https://github.com/uloco/bluloco.nvim/pull/79#issuecomment-2211834080

### CODE REVIEW

**Comment by uloco** [comment]
I was just going about fixing this. Thank you :) Do you think we should switch fg and bg? So it is easier to read?

**Comment by uloco** [comment]
I think the behavior changed a little as well with the LeapMatch and LeapLabel highlight groups. When I compare with the defaults...

How about something like this, so it is easier to read and differentiate?

```lua
    LeapMatch { fg = t.keyword, gui = "underline", sp = t.keyword },
    LeapLabel { bg = t.keyword, fg = t.bg },
    LeapBackdrop { fg = t.shade40 },
```

**Comment by uloco** [comment]
I am not using leap myself actively so please help me make it sensible.

**Comment by guoliang** [comment]
@uloca

With background looks nice too. I added the changes to the PR.

**Review by uloco — APPROVED** [review]
Thank you for finding and fixing this. Have a good one!

**Pull request merged**
